package errs

import "net/http"

var (
	CodeProjectListFailed                    = RegisterHTTPStatus("PROJECT-500-LIST", http.StatusInternalServerError)
	CodeProjectStatusFailed                  = RegisterHTTPStatus("PROJECT-500-STATUS", http.StatusInternalServerError)
	CodeProjectLocalListFailed               = RegisterHTTPStatus("PROJECT-500-LOCAL", http.StatusInternalServerError)
	CodeProjectInvalidBody                   = RegisterHTTPStatus("PROJECT-400-BODY", http.StatusBadRequest)
	CodeProjectAdminRequired                 = RegisterHTTPStatus("PROJECT-403-ADMIN", http.StatusForbidden)
	CodeProjectCreateFailed                  = RegisterHTTPStatus("PROJECT-400-CREATE", http.StatusBadRequest)
	CodeProjectDeployFailed                  = RegisterHTTPStatus("PROJECT-400-DEPLOY", http.StatusBadRequest)
	CodeProjectForwardFailed                 = RegisterHTTPStatus("PROJECT-400-FORWARD", http.StatusBadRequest)
	CodeProjectQuickFailed                   = RegisterHTTPStatus("PROJECT-400-QUICK", http.StatusBadRequest)
	CodeProjectTemplateSource                = RegisterHTTPStatus("PROJECT-400-TEMPLATE", http.StatusBadRequest)
	CodeProjectInvalidName                   = RegisterHTTPStatus("PROJECT-400-NAME", http.StatusBadRequest)
	CodeProjectInvalidContainer              = RegisterHTTPStatus("PROJECT-400-CONTAINER", http.StatusBadRequest)
	CodeProjectNotFound                      = RegisterHTTPStatus("PROJECT-404", http.StatusNotFound)
	CodeProjectContainerNotFound             = RegisterHTTPStatus("PROJECT-404-CONTAINER", http.StatusNotFound)
	CodeProjectDetailFailed                  = RegisterHTTPStatus("PROJECT-500-DETAIL", http.StatusInternalServerError)
	CodeProjectJobsFailed                    = RegisterHTTPStatus("PROJECT-500-JOBS", http.StatusInternalServerError)
	CodeProjectWorkbenchReadFailed           = RegisterHTTPStatus("PROJECT-500-WB-READ", http.StatusInternalServerError)
	CodeProjectWorkbenchImportFailed         = RegisterHTTPStatus("PROJECT-500-WB-IMPORT", http.StatusInternalServerError)
	CodeProjectWorkbenchPortResolveFailed    = RegisterHTTPStatus("PROJECT-500-WB-PORT-RESOLVE", http.StatusInternalServerError)
	CodeProjectWorkbenchPortMutateFailed     = RegisterHTTPStatus("PROJECT-500-WB-PORT-MUTATE", http.StatusInternalServerError)
	CodeProjectWorkbenchPortSuggestFailed    = RegisterHTTPStatus("PROJECT-500-WB-PORT-SUGGEST", http.StatusInternalServerError)
	CodeProjectWorkbenchServiceMutateFailed  = RegisterHTTPStatus("PROJECT-500-WB-SERVICE-MUTATE", http.StatusInternalServerError)
	CodeProjectWorkbenchResourceMutateFailed = RegisterHTTPStatus("PROJECT-500-WB-RESOURCE-MUTATE", http.StatusInternalServerError)
	CodeProjectWorkbenchModuleMutateFailed   = RegisterHTTPStatus("PROJECT-500-WB-MODULE-MUTATE", http.StatusInternalServerError)
	CodeProjectWorkbenchPreviewFailed        = RegisterHTTPStatus("PROJECT-500-WB-PREVIEW", http.StatusInternalServerError)
	CodeProjectWorkbenchApplyFailed          = RegisterHTTPStatus("PROJECT-500-WB-APPLY", http.StatusInternalServerError)
	CodeProjectWorkbenchRestoreFailed        = RegisterHTTPStatus("PROJECT-500-WB-RESTORE", http.StatusInternalServerError)
	CodeProjectArchivePlanFailed             = RegisterHTTPStatus("PROJECT-500-ARCHIVE-PLAN", http.StatusInternalServerError)
	CodeProjectArchiveFailed                 = RegisterHTTPStatus("PROJECT-500-ARCHIVE", http.StatusInternalServerError)
	CodeProjectStackFailed                   = RegisterHTTPStatus("PROJECT-500-STACK", http.StatusInternalServerError)
	CodeProjectContainerFailed               = RegisterHTTPStatus("PROJECT-500-CONTAINER", http.StatusInternalServerError)
	CodeProjectLogsFailed                    = RegisterHTTPStatus("PROJECT-500-LOGS", http.StatusInternalServerError)
	CodeProjectEnvReadFailed                 = RegisterHTTPStatus("PROJECT-500-ENV-READ", http.StatusInternalServerError)
	CodeProjectEnvWriteFailed                = RegisterHTTPStatus("PROJECT-500-ENV-WRITE", http.StatusInternalServerError)
	CodeProjectEnvTooLarge                   = RegisterHTTPStatus("PROJECT-400-ENV-SIZE", http.StatusBadRequest)
)
